### ISSUE TITLE
README examples not working

### ISSUE THREAD

**Issue by crbinz** [JuliaAstro/EarthOrientation.jl#1]
First, I apologize if you're not quite finished working through this package yet. Second, it has the potential to be a very useful package, I think! 

Now, my problem is that the examples in the README do not work. I can successfully run `EarthOrientation.update()`, but `eop = EOParams()` gives

```julia
ERROR: MethodError: no method matching EarthOrientation.EOParams()
Closest candidates are:
  EarthOrientation.EOParams(::String, ::String) at /Users/cbinz/.julia/v0.6/EarthOrientation/src/EarthOrientation.jl:135
  EarthOrientation.EOParams(::Any, ::Any) at /Users/cbinz/.julia/v0.6/EarthOrientation/src/EarthOrientation.jl:103
```

and I can't figure out `OptionalData` enough to pull what I need from (I think?) `EOP_DATA`. Any tips?

**Comment by helgee** [comment]
The package is basically done, I am just procrastinating on documenting it properly and releasing it 😐 

For now you can just skip the line `eop  = EOParams()` since it is included in `EarthOrientation.update()`. 
You can also omit the `eop` parameter from the data access calls, e.g.:
```julia
xp, yp = polarmotion(now())
```

**Comment by helgee** [comment]
I have cleaned up the docs and the first release is on its way to METADATA.
